name: billiards
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/billiard.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/billiard.png"
    
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Julee
      fonts:
       - asset: assets/fonts/Julee-Regular.ttf
    - family: Satisfy
      fonts:
       - asset: assets/fonts/Satisfy-Regular.ttf
    - family: Oswald
      fonts:
       - asset: assets/fonts/Oswald-Regular.ttf
    - family: Poppins
      fonts:
       - asset: assets/fonts/Poppins-Regular.ttf
    - family: PoppinsItalic
      fonts:
       - asset: assets/fonts/Poppins-BlackItalic.ttf
